### ISSUE TITLE
assembly -> alignment

### ISSUE THREAD

**Issue by colindaven** [mmpust/raspir#1]
Hi Marie,

very nice. 
One comment : assembly in the README.md is incorrect terminology, since this must be strictly distinguished from the assembly term used as a short form of de novo assembly. It causes all sorts of problems if people start confusing alignment and assembly (see biostars for v frequent confusion).

I'll have to give this a try soon, cheers.
Colin

**Comment by mmpust** [comment]
Hey Colin,
thank you for the notice indeed. I agree that using the correct terminology is crucial. The incorrect term has therefore been replaced. 

I am looking forward to hearing whether or not you benefit from using raspir. 
Best regards,
Marie
