### ISSUE TITLE
meaning of each column in output 

### ISSUE THREAD

**Issue by colindaven** [mmpust/raspir#15]
Hi @mmpust 

Questions
- what does each column mean?
- what is "significant" ?
- are only highly positive species mentioned, or are some threshold species listed ? What are the cutoffs ?

Thanks!

**Comment by colindaven** [comment]
Thanks for the explanations Marie.

For the most part the thresholds are exactly what I see. However I have one dataset where I think the pearson correlation is only 0.57, so below the 0.60 threshold. Thats's only one of hundreds though, most are over 0.85-0.99!


`1_CP013195_1_Prevotella_enoeca_strain_F0113__complete_genome_BAC                                                           0.5727   0.0      1e-05    0.072      uniform
`

**Comment by mmpust** [comment]
Hi Colin, thanks for pointing this out! The issue appeared due to an inconsistent rounding of decimals in the script. It has been adjusted now.
