### ISSUE TITLE
database

### ISSUE THREAD

**Issue by Luponsky** [mmpust/raspir#22]
Hello, 
Thanks to have developed Raspir, I would like to use it to analyze my data.
However, I'm not be able to download the DB, it seems that the link is broken.
Could you kindly help me??
Cheers,
L

**Comment by mmpust** [comment]
Thanks for your interest in _raspir_. The reference DB is from 2019 and hence no longer up-to-date. I would thus recommend to use your own multi-fast file or the customized database provided by _Wochenende_ (https://github.com/MHH-RCUG/Wochenende). Please be aware that all databases have been developed with the human airway ecosystem in mind.

Reference database:
https://drive.google.com/drive/folders/1q1btJCxtU15XXqfA-iCyNwgKgQq0SrG4?usp=sharing

I hope this helps!
