### ISSUE TITLE
No regions or BED file have been provided

### ISSUE THREAD

**Issue by ailtonpcf** [mmpust/raspir#23]
Hey,

I'm trying to run raspir and as soon I get my sam from bowtie2, samtools view fails:

samtools view -hM -q 20 c001.sam > c001.mq20.sam
[main_samview] no regions or BED file have been provided. Aborting.

Is it safe to remove the -M flag?

This is my conda env:

name: raspir
channels:
  - bioconda
  - conda-forge
dependencies:
  - trimmomatic
  - samtools=1.9
  - bowtie2=2.3.4
  - python=3.7
  - pip
  - pip:
    - pandas
    - statsmodels
    - matplotlib

Bests,
Ailton.

**Comment by mmpust** [comment]
Hi Ailton, thank you for your interest in using _raspir_. If you're not focused on a specific genome/region within a multi-FASTA alignment and wish to apply the algorithm to the entire file, it is safe to remove the `-M` flag.
